services:
    cld_text_collection.validator.constraint_guesser.text_collection:
        class: Cld\Bundle\TextCollectionBundle\Validator\ConstraintGuesser\TextCollectionGuesser
        tags:
            - { name: pim_catalog.constraint_guesser.attribute }
